import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenCheck, CalendarDays, ChartNoAxesCombined, Clock3, Flame, Target, Zap } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Panel, Tag } from "@/components/ui";
export const Route=createFileRoute("/dashboard")({head:()=>({meta:[{title:"Learning Dashboard — Brain Nest"},{name:"description",content:"Track study progress, weak topics, quiz accuracy, and your revision plan."},{property:"og:title",content:"Learning Dashboard — Brain Nest"},{property:"og:description",content:"A clear view of your progress and next best study actions."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Dashboard});
function Dashboard(){return <><PageHero eyebrow="Learning dashboard" title="Good evening, Aryan." copy="You’re building momentum. Here’s where to focus next."/><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi icon={Clock3} value="6.4h" label="Study time" change="+18% this week"/><Kpi icon={Target} value="76%" label="Quiz accuracy" change="+7% this week"/><Kpi icon={BookOpenCheck} value="14" label="Topics mastered" change="3 this week"/><Kpi icon={Flame} value="4 days" label="Study streak" change="Personal best: 9"/></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Weekly activity</h2><p className="mt-1 text-sm text-muted-foreground">Focused learning minutes</p></div><Tag>6h 24m</Tag></div><div className="mt-8 flex h-52 items-end justify-between gap-3">{[45,70,40,85,62,96,30].map((h,i)=><div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="rounded-sm bg-primary/20 p-1" style={{height:`${h}%`}}><div className="h-full w-full rounded-sm bg-primary"/></div><span className="text-center text-[10px] text-muted-foreground">{["M","T","W","T","F","S","S"][i]}</span></div>)}</div></Panel><Panel className="p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-md bg-highlight/10 text-highlight"><Zap size={20}/></span><div><h2 className="font-bold">Revision priority</h2><p className="text-xs text-muted-foreground">Based on recent performance</p></div></div><div className="mt-6 space-y-3"><Priority title="Electromagnetic induction" score="52%" tone="high"/><Priority title="Ray optics" score="64%" tone="high"/><Priority title="Alternating current" score="71%" tone="medium"/></div><Link to="/study" className="mt-6 flex items-center justify-between border-t border-border pt-4 text-sm font-bold text-primary">Start focused review <ArrowRight size={16}/></Link></Panel></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel className="p-5"><h2 className="flex items-center gap-2 font-bold"><CalendarDays size={18} className="text-primary"/>Today’s plan</h2><div className="mt-5 space-y-4"><Task done title="Revise magnetic flux notes" time="20 min"/><Task title="Complete induction quiz" time="15 min"/><Task title="Review two long answers" time="25 min"/></div></Panel><Panel className="p-5"><h2 className="flex items-center gap-2 font-bold"><ChartNoAxesCombined size={18} className="text-primary"/>Subject progress</h2><div className="mt-5 space-y-5"><Progress label="Physics" value={74}/><Progress label="Mathematics" value={62}/><Progress label="Chemistry" value={48}/></div></Panel></div></section></>}
function Kpi({icon:Icon,value,label,change}:{icon:any;value:string;label:string;change:string}){return <Panel className="p-5"><Icon size={19} className="text-primary"/><p className="mt-5 font-display text-3xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-xs text-primary">{change}</p></Panel>}
function Priority({title,score,tone}:{title:string;score:string;tone:string}){return <div className="flex items-center justify-between rounded-md bg-secondary p-3"><div><p className="text-sm font-bold">{title}</p><p className={`mt-1 text-xs ${tone==="high"?"text-highlight":"text-warning"}`}>{tone==="high"?"Needs focus":"Review soon"}</p></div><strong>{score}</strong></div>}
function Task({done=false,title,time}:{done?:boolean;title:string;time:string}){return <div className="flex items-center gap-3"><span className={`grid size-6 place-items-center rounded-full border ${done?"border-success bg-success/10 text-success":"border-border"}`}>{done&&"✓"}</span><div className="flex-1"><p className={`text-sm font-semibold ${done?"text-muted-foreground line-through":""}`}>{title}</p></div><span className="text-xs text-muted-foreground">{time}</span></div>}
function Progress({label,value}:{label:string;value:number}){return <div><div className="mb-2 flex justify-between text-sm"><span>{label}</span><strong>{value}%</strong></div><div className="h-2 rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${value}%`}}/></div></div>}
