import { createFileRoute } from "@tanstack/react-router";
import { Award, Bell, BookOpen, GraduationCap, Settings2, UserRound } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Button, Panel, Tag } from "@/components/ui";
import { AccountCard } from "@/components/account-card";
import { useAuth } from "@/hooks/use-auth";
function ProfileName(){const {user}=useAuth();return <h2 className="mt-4 text-xl font-bold">{(user?.user_metadata?.['full_name'] as string)||user?.email||"Guest student"}</h2>}
export const Route=createFileRoute("/profile")({head:()=>({meta:[{title:"Student Profile — Brain Nest"},{name:"description",content:"Manage your Brain Nest learning preferences and study profile."},{property:"og:title",content:"Student Profile — Brain Nest"},{property:"og:description",content:"Your learning preferences, achievements, and account details."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Profile});
function Profile(){return <><PageHero eyebrow="Student profile" title="Your learning, your way" copy="Keep your goals and study preferences aligned so Brain Nest can personalize every session."/><section className="mx-auto grid max-w-6xl gap-6 px-4 py-10 sm:px-6 lg:grid-cols-[0.7fr_1.3fr] lg:px-8"><div className="space-y-6"><Panel className="p-6 text-center"><span className="mx-auto grid size-20 place-items-center rounded-full border border-primary/30 bg-primary/10 text-primary"><UserRound size={38}/></span><ProfileName/><p className="mt-1 text-sm text-muted-foreground">Higher secondary student</p><div className="mt-5 flex justify-center gap-2"><Tag>Physics</Tag><Tag tone="pink">Exam prep</Tag></div></Panel><Panel className="p-5"><h3 className="flex items-center gap-2 font-bold"><Award size={18} className="text-warning"/>Achievements</h3><div className="mt-5 grid grid-cols-2 gap-3"><Badge value="4" label="Day streak"/><Badge value="14" label="Mastered"/><Badge value="28" label="Quizzes"/><Badge value="680" label="Points"/></div></Panel></div><div className="space-y-6"><AccountCard/><Panel className="p-5 sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><Settings2 size={19} className="text-primary"/>Learning preferences</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Education level" value="Higher secondary"/><Field label="Primary goal" value="Board exam preparation"/><Field label="Preferred study style" value="Concise notes + practice"/><Field label="Daily study target" value="60 minutes"/></div><Button className="mt-6">Save preferences</Button></Panel><Panel className="p-5 sm:p-6"><h2 className="text-lg font-bold">Your subjects</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Subject icon={BookOpen} label="Physics"/><Subject icon={GraduationCap} label="Mathematics"/><button className="min-h-24 rounded-md border border-dashed border-border text-sm font-bold text-muted-foreground hover:border-primary hover:text-primary">+ Add subject</button></div></Panel><Panel className="flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-md bg-secondary text-primary"><Bell size={18}/></span><div className="flex-1"><p className="font-bold">Study reminders</p><p className="text-sm text-muted-foreground">Daily at 7:30 PM</p></div><button aria-label="Toggle reminders" className="relative h-6 w-11 rounded-full bg-primary"><span className="absolute right-1 top-1 size-4 rounded-full bg-primary-foreground"/></button></Panel></div></section></>}
function Field({label,value}:{label:string;value:string}){return <label className="text-sm font-semibold">{label}<select defaultValue={value} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary"><option>{value}</option></select></label>}
function Badge({value,label}:{value:string;label:string}){return <div className="rounded-md bg-secondary p-3"><p className="font-display text-xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>}
function Subject({icon:Icon,label}:{icon:any;label:string}){return <button className="flex min-h-24 flex-col items-start justify-between rounded-md border border-border bg-secondary p-4 text-left hover:border-primary"><Icon className="text-primary" size={19}/><span className="text-sm font-bold">{label}</span></button>}
