import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { ArrowUpRight, BarChart3, FileSearch, Flame, Layers3, Loader2, ScanSearch } from "lucide-react";
import { useState } from "react";
import { PageHero } from "@/components/page-hero";
import { Button, Panel, Tag } from "@/components/ui";
import { AiOutput } from "@/components/ai-output";
import { SignInGate } from "@/components/sign-in-gate";
import { useAuth } from "@/hooks/use-auth";
import { analyzeQuestions } from "@/lib/study.functions";

export const Route = createFileRoute("/question-analysis")({ head: () => ({ meta: [{ title: "Question Analysis — Brain Nest" }, { name: "description", content: "Find repeated question patterns, high-priority topics, and exam prediction indicators." }, { property: "og:title", content: "Question Pattern Analysis — Brain Nest" }, { property: "og:description", content: "See what matters most across previous exam papers." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: AnalysisPage });
const topics = [{name:"Electromagnetic induction", count:12, likelihood:"Very high", width:"92%"},{name:"Alternating current", count:9, likelihood:"High", width:"76%"},{name:"Ray optics", count:7, likelihood:"High", width:"64%"},{name:"Semiconductor devices", count:5, likelihood:"Medium", width:"48%"}];
function AnalyzeYourPapers(){const {user}=useAuth();const run=useServerFn(analyzeQuestions);const [papers,setPapers]=useState("");const [subject,setSubject]=useState("Physics");const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);const [result,setResult]=useState<string|null>(null);
async function go(){setLoading(true);setError(null);setResult(null);try{const r=await run({data:{papers,subject}});if(r.ok)setResult(r.text);else setError(r.error);}catch{setError("Please paste a few more past questions and try again.");}setLoading(false);}
return <Panel className="mb-6 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Analyze your own past papers</h2><p className="mt-1 text-sm text-muted-foreground">Paste questions from several previous papers to find repeated topics and likely picks.</p></div><select value={subject} onChange={e=>setSubject(e.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{["Physics","Chemistry","Biology","Mathematics","Computer Science","English","History","Economics"].map(s=><option key={s}>{s}</option>)}</select></div><textarea value={papers} onChange={e=>setPapers(e.target.value)} rows={6} placeholder="Paste past exam questions here (one per line works best)" className="mt-4 w-full rounded-md border border-input bg-background p-3 text-sm outline-none focus:border-primary"/>{user?<Button className="mt-4" disabled={loading||papers.trim().length<40} onClick={go}>{loading?<Loader2 className="animate-spin" size={18}/>:<ScanSearch size={18}/>}{loading?"Analyzing…":"Analyze patterns"}</Button>:<div className="mt-4"><SignInGate action="analyze your papers"/></div>}{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}{result&&<div className="mt-6 border-t border-border pt-5"><AiOutput text={result}/></div>}</Panel>}
function AnalysisPage(){return <><PageHero eyebrow="Question intelligence" title="See the patterns behind the paper" copy="Compare previous-year questions, spot repeated concepts, and focus your time where it can make the biggest difference." />
<section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><AnalyzeYourPapers/><p className="mb-4 text-xs font-bold uppercase text-muted-foreground">Sample analysis</p><div className="grid gap-4 sm:grid-cols-3"><Stat icon={FileSearch} value="126" label="Questions analyzed" /><Stat icon={Layers3} value="18" label="Recurring concepts" /><Stat icon={ScanSearch} value="84%" label="Syllabus coverage" /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Topic frequency</h2><p className="mt-1 text-sm text-muted-foreground">Based on 8 papers from 2018–2025</p></div><Tag>Physics</Tag></div><div className="mt-7 space-y-6">{topics.map(t=><div key={t.name}><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold">{t.name}</p><p className="mt-1 text-xs text-muted-foreground">Appeared {t.count} times</p></div><span className="text-xs font-bold text-primary">{t.likelihood}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:t.width}} /></div></div>)}</div></Panel><div className="space-y-6"><Panel className="p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-md bg-highlight/10 text-highlight"><Flame /></span><div><p className="font-bold">Hot prediction</p><p className="text-xs text-muted-foreground">Strong cross-paper signal</p></div></div><h3 className="mt-5 text-xl font-bold">Faraday’s law applications</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Likely as a five-mark derivation or transformer efficiency problem.</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><Tag tone="pink">89% indicator</Tag><ArrowUpRight className="text-highlight" /></div></Panel><Panel className="p-5"><div className="flex items-center gap-3"><BarChart3 className="text-primary"/><h3 className="font-bold">Question format mix</h3></div><div className="mt-5 space-y-4"><Mix label="Long answer" value="42%"/><Mix label="Numerical" value="34%"/><Mix label="Short answer" value="24%"/></div></Panel></div></div></section></>}
function Stat({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <Panel className="p-5"><Icon className="text-primary" size={20}/><p className="mt-5 font-display text-3xl font-bold">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></Panel>}
function Mix({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>}
