import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Clock3, RotateCcw, Trophy } from "lucide-react";
import { useState } from "react";
import { PageHero } from "@/components/page-hero";
import { Button, Panel, Tag } from "@/components/ui";
export const Route = createFileRoute("/quiz")({ head:()=>({meta:[{title:"Adaptive Quiz — Brain Nest"},{name:"description",content:"Practice with focused quizzes and instant explanations."},{property:"og:title",content:"Adaptive Quiz — Brain Nest"},{property:"og:description",content:"Build exam confidence with targeted practice."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:QuizPage});
const answers=["The change in magnetic flux","The total magnetic field","The resistance of the coil","The charge stored in the circuit"];
function QuizPage(){const [answer,setAnswer]=useState<number|null>(null); const [done,setDone]=useState(false); return <><PageHero eyebrow="Adaptive practice" title="Test recall. Strengthen understanding." copy="Short, focused practice that adapts to the concepts you need to revisit."/><section className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8"><div className="mb-4 flex items-center justify-between text-sm"><Tag>Physics • 10 questions</Tag><span className="flex items-center gap-2 text-muted-foreground"><Clock3 size={16}/>08:42</span></div><div className="mb-6 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full w-[30%] rounded-full bg-primary"/></div><Panel className="p-5 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.15em] text-primary">Question 3 of 10</p><h1 className="mt-4 text-xl font-bold leading-8 sm:text-2xl">According to Faraday’s law, the induced EMF in a closed circuit is proportional to:</h1><div className="mt-7 grid gap-3">{answers.map((a,i)=><button key={a} disabled={done} onClick={()=>setAnswer(i)} className={`flex min-h-14 items-center gap-4 rounded-md border p-4 text-left text-sm transition ${answer===i?"border-primary bg-primary/10":"border-border bg-secondary hover:border-primary/50"}`}><span className={`grid size-7 shrink-0 place-items-center rounded-full border text-xs font-bold ${answer===i?"border-primary text-primary":"border-border text-muted-foreground"}`}>{String.fromCharCode(65+i)}</span>{a}</button>)}</div>{done&&<div className={`mt-6 rounded-md border p-4 ${answer===0?"border-success/30 bg-success/10":"border-highlight/30 bg-highlight/10"}`}><div className="flex items-center gap-2 font-bold"><CheckCircle2 size={18} className="text-success"/>The change in magnetic flux</div><p className="mt-2 text-sm leading-6 text-muted-foreground">Faraday’s law states that induced EMF equals the negative rate of change of magnetic flux linkage.</p></div>}<div className="mt-7 flex justify-end"><Button disabled={answer===null} onClick={()=>setDone(true)}>{done?<><RotateCcw size={17}/>Review answer</>:"Check answer"}</Button></div></Panel><div className="mt-6 grid gap-4 sm:grid-cols-3"><Mini icon={Trophy} value="680" label="Practice points"/><Mini value="76%" label="Current accuracy"/><Mini value="4" label="Day streak"/></div></section></>}
function Mini({icon:Icon,value,label}:{icon?:any;value:string;label:string}){return <Panel className="flex items-center gap-3 p-4">{Icon&&<Icon size={18} className="text-warning"/>}<div><p className="font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></Panel>}
